defmodule FW.Release.InitUnits do
  @moduledoc """
  Custom Mix release step that detects the running init system and
  writes service unit files into the assembled release.

  Runs **after** `:assemble` (so the release binary already exists)
  and **before** `:tar` (so the units are included in the tarball).

  Configure in `mix.exs`:

      releases: [
        fw: [
          include_executables_for: [:unix],
          steps: [:assemble, &FW.Release.InitUnits.run/1, :tar]
        ]
      ]

  ## Generated files

  All files are written under `<release_root>/releases/<vsn>/init/`:

    - `systemd/fw.service`
    - `runit/fw/run`, `runit/fw/finish`, `runit/fw/log/run`
    - `s6/fw/run`, `s6/fw/finish`, `s6/fw/type`
    - `s6/fw-log/run`, `s6/fw-log/type`
    - `README.md`

  ## Detection order

  1. **systemd** — `/run/systemd/private` exists, or `INVOCATION_ID`
     env var is set, or PID-1 (`/proc/1/comm`) is `systemd`.
  2. **runit** — `/run/runit` exists, `/sbin/runit-init` exists,
     or PID-1 is `runit`.
  3. **s6** — `/run/s6` exists, `s6-svscan` in PATH, or PID-1 is `s6`.
  4. **unknown** — warning printed, all templates still written.
  """

  @doc """
  Entry point called by the Mix release pipeline.
  Receives and returns the `%Mix.Release{}` struct unchanged.
  """
  def run(%Mix.Release{} = release) do
    init_dir = init_dir(release)
    :ok = File.mkdir_p(init_dir)

    init = detect_init()
    log("detected init system: #{init}")

    write_readme(init_dir, release)
    write_for(init, init_dir, release)

    log("unit files written to #{Path.relative_to_cwd(init_dir)}/")
    release
  end

  # ---------------------------------------------------------------------------
  # Release path helpers
  # ---------------------------------------------------------------------------

  # Write units under releases/<vsn>/init/ inside the assembled release root.
  # They will be included in the .tar.gz produced by the :tar step.
  defp init_dir(%Mix.Release{version: vsn, path: root}) do
    Path.join([root, "releases", vsn, "init"])
  end

  # Absolute path to the release binary (used in generated unit files).
  defp bin_path(%Mix.Release{name: name, path: root}) do
    Path.join([root, "bin", to_string(name)])
  end

  # ---------------------------------------------------------------------------
  # Init detection
  # ---------------------------------------------------------------------------

  defp detect_init do
    cond do
      systemd?() -> :systemd
      runit?() -> :runit
      s6?() -> :s6
      true -> :unknown
    end
  end

  defp systemd? do
    File.exists?("/run/systemd/private") or
      System.get_env("INVOCATION_ID") != nil or
      String.contains?(pid1_comm(), "systemd")
  end

  defp runit? do
    File.exists?("/run/runit") or
      File.exists?("/sbin/runit-init") or
      String.contains?(pid1_comm(), "runit")
  end

  defp s6? do
    File.exists?("/run/s6") or
      System.find_executable("s6-svscan") != nil or
      String.contains?(pid1_comm(), "s6")
  end

  defp pid1_comm do
    case File.read("/proc/1/comm") do
      {:ok, comm} -> String.trim(comm)
      _ -> ""
    end
  end

  # ---------------------------------------------------------------------------
  # Dispatch
  # ---------------------------------------------------------------------------

  defp write_for(:unknown, init_dir, release) do
    log(
      "WARNING: could not detect a supported init system (systemd/runit/s6). " <>
        "Writing all templates anyway. " <>
        "See #{Path.join(init_dir, "README.md")} for install instructions."
    )

    # Write all templates so the tarball is self-contained regardless.
    write_systemd(init_dir, release)
    write_runit(init_dir, release)
    write_s6(init_dir, release)
  end

  defp write_for(init, init_dir, release) do
    # Always write all templates — the tarball may be installed on a
    # different machine with a different init system.
    write_systemd(init_dir, release)
    write_runit(init_dir, release)
    write_s6(init_dir, release)
    log("detected #{init} — see init/#{init}/ for the recommended unit files")
  end

  # ---------------------------------------------------------------------------
  # systemd
  # ---------------------------------------------------------------------------

  defp write_systemd(init_dir, release) do
    dir = Path.join(init_dir, "systemd")
    :ok = File.mkdir_p(dir)
    write_file(Path.join(dir, "fw.service"), systemd_unit(release))
  end

  defp systemd_unit(release) do
    bin = bin_path(release)

    """
    # ~/.config/systemd/user/fw.service
    #
    # Generated by `mix release` via FW.Release.InitUnits.
    #
    # Install:
    #   mkdir -p ~/.config/systemd/user
    #   cp releases/#{release.version}/init/systemd/fw.service ~/.config/systemd/user/fw.service
    #   systemctl --user daemon-reload
    #   systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    #   systemctl --user enable --now fw
    #   journalctl --user -u fw -f
    #
    # ExecStart points to the release binary produced by `mix release`.
    # If you move the release, update ExecStart accordingly.

    [Unit]
    Description=fw — feature-wallpaper Wayland wallpaper daemon
    Documentation=https://github.com/Skartorion/feature-wallpaper
    After=graphical-session.target
    PartOf=graphical-session.target

    [Service]
    Type=simple
    ExecStart=#{bin} start
    ExecStop=#{bin} stop

    KillSignal=SIGTERM
    KillMode=mixed
    TimeoutStopSec=10

    Restart=on-failure
    RestartSec=3s

    # WAYLAND_DISPLAY is inherited from the compositor session.
    # Propagate it once after login:
    #   systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    # Or add to hyprland.conf:
    #   exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    Environment=LANG=en_US.UTF-8

    StandardOutput=journal
    StandardError=journal
    SyslogIdentifier=fw

    [Install]
    WantedBy=graphical-session.target
    """
  end

  # ---------------------------------------------------------------------------
  # runit
  # ---------------------------------------------------------------------------

  defp write_runit(init_dir, release) do
    base = Path.join([init_dir, "runit", "fw"])
    log_dir = Path.join(base, "log")
    :ok = File.mkdir_p(log_dir)

    write_file(Path.join(base, "run"), runit_run(release), mode: 0o755)
    write_file(Path.join(base, "finish"), runit_finish(), mode: 0o755)
    write_file(Path.join(log_dir, "run"), runit_log_run(), mode: 0o755)
  end

  defp runit_run(release) do
    bin = bin_path(release)

    """
    #!/bin/sh
    # /etc/sv/fw/run  — runit service run script
    #
    # Generated by `mix release` via FW.Release.InitUnits.
    #
    # Install:
    #   sudo cp -r releases/#{release.version}/init/runit/fw /etc/sv/fw
    #   sudo ln -s /etc/sv/fw /var/service/fw
    #   sv status fw
    #
    # Set FW_USER to the user that should run the daemon.

    FW_USER=YOURUSER
    FW_UID=$(id -u "${FW_USER}" 2>/dev/null || echo 1000)

    exec chpst -u "${FW_USER}:${FW_USER}" \\
      env WAYLAND_DISPLAY=wayland-1 \\
          XDG_RUNTIME_DIR=/run/user/${FW_UID} \\
      #{bin} start
    """
  end

  defp runit_finish do
    """
    #!/bin/sh
    # Called by runit when the service exits.
    # $1 = exit code, $2 = signal (-1 if exited without a signal)
    echo "[fw] exited: code=$1 signal=$2" >&2
    """
  end

  defp runit_log_run do
    """
    #!/bin/sh
    # Log consumer — pipes stdout/stderr through svlogd.
    exec svlogd -tt /var/log/fw
    """
  end

  # ---------------------------------------------------------------------------
  # s6
  # ---------------------------------------------------------------------------

  defp write_s6(init_dir, release) do
    base = Path.join([init_dir, "s6", "fw"])
    log_dir = Path.join([init_dir, "s6", "fw-log"])
    :ok = File.mkdir_p(base)
    :ok = File.mkdir_p(log_dir)

    write_file(Path.join(base, "run"), s6_run(release), mode: 0o755)
    write_file(Path.join(base, "finish"), s6_finish(), mode: 0o755)
    write_file(Path.join(base, "type"), "longrun\n")
    write_file(Path.join(log_dir, "run"), s6_log_run(), mode: 0o755)
    write_file(Path.join(log_dir, "type"), "longrun\n")
  end

  defp s6_run(release) do
    bin = bin_path(release)

    """
    #!/bin/execlineb -P
    # s6 service run script for fw
    #
    # Generated by `mix release` via FW.Release.InitUnits.
    #
    # Install:
    #   sudo cp -r releases/#{release.version}/init/s6/fw /etc/s6/sv/fw
    #   sudo cp -r releases/#{release.version}/init/s6/fw-log /etc/s6/sv/fw-log
    #   # Then symlink into your s6 scan dir or add to s6-rc source database.
    #
    # Replace YOURUSER with the user that should run the daemon.

    importas -D "wayland-1" WAYLAND_DISPLAY WAYLAND_DISPLAY
    importas -D "/run/user/1000" XDG_RUNTIME_DIR XDG_RUNTIME_DIR

    s6-setuidgid YOURUSER

    #{bin} start
    """
  end

  defp s6_finish do
    """
    #!/bin/execlineb
    foreground { s6-echo "[fw] service exited" }
    exit 0
    """
  end

  defp s6_log_run do
    """
    #!/bin/execlineb -P
    s6-log -d3 T /var/log/fw
    """
  end

  # ---------------------------------------------------------------------------
  # README
  # ---------------------------------------------------------------------------

  defp write_readme(init_dir, release) do
    write_file(Path.join(init_dir, "README.md"), readme(release))
  end

  defp readme(release) do
    vsn = release.version

    """
    # fw — Init Unit Files

    Generated by `mix release` (v#{vsn}) via `FW.Release.InitUnits`.
    All three init managers are included; use the one matching your system.

    ## systemd (recommended for Hyprland / sway / Wayland)

    ```bash
    mkdir -p ~/.config/systemd/user
    cp releases/#{vsn}/init/systemd/fw.service ~/.config/systemd/user/fw.service
    systemctl --user daemon-reload
    systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    systemctl --user enable --now fw
    journalctl --user -u fw -f
    ```

    For Hyprland, add to `hyprland.conf`:
    ```
    exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    ```

    ## runit (Void Linux, artix-runit, etc.)

    ```bash
    # Edit run: set FW_USER to your username
    nano releases/#{vsn}/init/runit/fw/run

    sudo cp -r releases/#{vsn}/init/runit/fw /etc/sv/fw
    sudo ln -s /etc/sv/fw /var/service/fw
    sv status fw
    ```

    ## s6 (artix-s6, Chimera Linux, etc.)

    ```bash
    # Edit run: replace YOURUSER with your username
    nano releases/#{vsn}/init/s6/fw/run

    sudo cp -r releases/#{vsn}/init/s6/fw /etc/s6/sv/fw
    sudo cp -r releases/#{vsn}/init/s6/fw-log /etc/s6/sv/fw-log
    # Symlink into your s6 scan dir or add to s6-rc source database.
    ```

    ## Notes

    - `bin/fw start` runs the BEAM VM in the **foreground** — correct for all three supervisors.
    - `SIGTERM` allows OTP to drain supervision trees gracefully.
    - ExecStart / chpst / s6-setuidgid paths point to this release root.
      If you move the release, update those paths.
    """
  end

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp write_file(path, content, opts \\ []) do
    :ok = File.mkdir_p(Path.dirname(path))
    :ok = File.write(path, content)

    if mode = Keyword.get(opts, :mode) do
      File.chmod!(path, mode)
    end
  end

  defp log(msg), do: Mix.shell().info("* [fw_init_units] #{msg}")
end
